#spring.datasource.url=
spring.datasource.url=
#spring.datasource.url=
spring.datasource.username=
#spring.datasource.password=
spring.datasource.password=

#spring.cloud.gcp.sql.database-name=
#spring.cloud.gcp.sql.instance-connection-name=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Esta línea especifica la clase del controlador JDBC que se 
#utilizará para conectar a la base de datos MySQL.

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#Esta línea define el dialecto de Hibernate que se utilizará.
#En este caso, 
#estás utilizando el dialecto para MySQL 8.


spring.jpa.open-in-view=false
#Esta línea desactiva la característica 
#“Open Session in View” de Spring, que puede 
#mantener abierta una sesión de Hibernate durante 
#toda la duración de una solicitud HTTP.

spring.session.store-type=none
#Esta línea desactiva el almacenamiento
#de sesiones de Spring. Esto significa que no se 
#almacenarán datos de sesión entre solicitudes.


spring.jpa.show-sql=true
#Esta línea habilita la visualización
#de las consultas SQL generadas por 
#Hibernate en la consola.


spring.jpa.hibernate.ddl-auto=update
#Esta línea desactiva la generación
#automática del esquema de la base de datos
#por parte de Hibernate. Esto significa que
#Hibernate no creará, actualizará ni verificará
#automáticamente las tablas de tu base de datos.


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.username=athomlab.pe@gmail.com
spring.mail.password=omdnexyqogjktmhj
#spring.mail.password=xqnwgyhszkvlctrd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.allow-circular-references=true

#JWT
jwt.secret=secret
jwt.expiration=3600
jwt.accessTokenCookieName=AuthToken
